Specify versions for Arduino core and libraries
Updated Arduino CLI commands to specify versions for board core and library installations. Added validation for the serial port format before uploading firmware.

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -19,12 +19,12 @@ jobs:
 
       - name: Install required board core
         run: | 
-          & "$Env:RUNNER_TOOL_CACHE\arduino-cli\arduino-cli.exe" --config-file config.yaml core install arduino:avr 
+          & "$Env:RUNNER_TOOL_CACHE\arduino-cli\arduino-cli.exe" --config-file config.yaml core install arduino:avr@1.8.7
           
       - name: Install custom Arduino libraries (Windows)
         shell: powershell
         run: |
-          & "$Env:RUNNER_TOOL_CACHE\arduino-cli\arduino-cli.exe" --config-file config.yaml lib install MQTTESP8266
+          & "$Env:RUNNER_TOOL_CACHE\arduino-cli\arduino-cli.exe" --config-file config.yaml lib install "MQTTESP8266@5.1.2"
 
       - name: Set configs (Windows)
         shell: powershell
@@ -38,6 +38,11 @@ jobs:
           & "$Env:RUNNER_TOOL_CACHE\arduino-cli\arduino-cli.exe" --config-file config.yaml compile --fqbn arduino:avr:uno ./ --output-dir build
 
       - name: Upload firmware to Arduino
+        env:
+          SERIAL_PORT: ${{ github.event.deployment.payload.serial_port }}
         run: |
-          $port = "${{ github.event.deployment.payload.serial_port }}"
-          & "$Env:RUNNER_TOOL_CACHE\arduino-cli\arduino-cli.exe" --config-file config.yaml upload --fqbn arduino:avr:uno --port $port --input-dir build
+          if ($env:SERIAL_PORT -notmatch '^COM\d+$') {
+            Write-Error "Invalid serial port format: $env:SERIAL_PORT"
+            exit 1
+          }
+          & "$Env:RUNNER_TOOL_CACHE\arduino-cli\arduino-cli.exe" --config-file config.yaml upload --fqbn arduino:avr:uno --port $env:SERIAL_PORT --input-dir build
